# Generated by Django 3.2.9 on 2021-11-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='ssh_port',
            field=models.IntegerField(default=255),
        ),
    ]
